categories:
  GedankenfolgerSitepackage:
    label: 'Gedankenfolger Sitepackage'
  GedankenfolgerSitepackage.settings:
    label: 'Settings'
    parent: GedankenfolgerSitepackage
  GedankenfolgerSitepackage.menus:
    label: 'Menus'
    parent: GedankenfolgerSitepackage
  GedankenfolgerSitepackage.style:
    label: 'Style'
    parent: GedankenfolgerSitepackage
  GedankenfolgerSitepackage.address:
    label: 'Address'
    parent: GedankenfolgerSitepackage

settings:
  GedankenfolgerSitepackage.space_before_class:
    label: 'Default space before'
    category: GedankenfolgerSitepackage.style
    description: ''
    type: string
    default: 'mt-5'

  GedankenfolgerSitepackage.space_after_class:
    label: 'Default space after'
    category: GedankenfolgerSitepackage.style
    description: ''
    type: string
    default: 'mb-5'
  GedankenfolgerSitepackage.basePath:
    label: 'Public base path'
    type: string
    default: 'EXT:gedankenfolger_sitepackage_min/Resources/Public/'
    category: GedankenfolgerSitepackage.settings

  GedankenfolgerSitepackage.navSticky:
    label: 'Sticky menu root uid'
    description: 'The sysfolder which holds the pages for the menu'
    category: GedankenfolgerSitepackage.menus
    type: int
    default: 0

  GedankenfolgerSitepackage.navSocial:
    label: 'Social menu root uid'
    description: 'The sysfolder which holds the pages for the menu'
    category: GedankenfolgerSitepackage.menus
    type: int
    default: 0

  GedankenfolgerSitepackage.navFooter1:
    label: 'Footer 1 root uid'
    description: 'The sysfolder which holds the pages for the menu'
    category: GedankenfolgerSitepackage.menus
    type: int
    default: 0

  GedankenfolgerSitepackage.navFooter2:
    label: 'Footer 2 root uid'
    description: 'The sysfolder which holds the pages for the menu'
    category: GedankenfolgerSitepackage.menus
    type: int
    default: 0

  GedankenfolgerSitepackage.sysfolder_uid:
    label: 'Address sysfolder uid'
    category: GedankenfolgerSitepackage.address
    description: 'Folder which holds the address entries'
    type: int
    default: 38