name: gedankenfolger/text
typeName: gedankenfolger_text
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: Gedankenfolger/Header
    type: Basic
  -
    identifier: bodytext
    useExistingField: true
    enableRichtext: true
    richtextConfiguration: full
  - identifier: Gedankenfolger/Appearance
    type: Basic
